/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    users: User;
    pages: Page;
    media: Media;
  };
  globals: {
    navigation: Navigation;
    footer: Footer;
  };
}
export interface User {
  id: string;
  firstName?: string;
  lastName?: string;
  roles: ('admin' | 'editor' | 'public')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string;
  resetPasswordExpiration?: string;
  salt?: string;
  hash?: string;
  loginAttempts?: number;
  lockUntil?: string;
  password?: string;
}
export interface Page {
  id: string;
  name: string;
  slug?: string;
  meta: {
    title: string;
    description: string;
  };
  content: {
    layout?: (
      | {
          maxWidth: 'full' | 'large' | 'medium';
          heading: string;
          description: string;
          tags?: {
            text: string;
            icon?: string;
            id?: string;
          }[];
          buttonLinks?: {
            color: 'primary' | 'neutral';
            variant: 'outlined' | 'solid';
            size: 'sm' | 'md' | 'lg';
            link: {
              text: string;
              icon?: string;
              iconPosition: 'none' | 'left' | 'right';
              newTab?: boolean;
              type: 'reference' | 'external';
              reference: {
                value: string | Page;
                relationTo: 'pages';
              };
              url: string;
            };
            id?: string;
          }[];
          id?: string;
          blockName?: string;
          blockType: 'hero';
        }
      | {
          maxWidth: 'full' | 'large' | 'medium';
          heading: string;
          sectionId?: string;
          layout?: (
            | {
                content: {
                  [k: string]: unknown;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'content';
              }
            | {
                color: 'primary' | 'neutral';
                variant: 'outlined' | 'solid';
                size: 'sm' | 'md' | 'lg';
                link: {
                  text: string;
                  icon?: string;
                  iconPosition: 'none' | 'left' | 'right';
                  newTab?: boolean;
                  type: 'reference' | 'external';
                  reference: {
                    value: string | Page;
                    relationTo: 'pages';
                  };
                  url: string;
                };
                margin?: boolean;
                id?: string;
                blockName?: string;
                blockType: 'buttonLink';
              }
            | {
                questions?: {
                  question: string;
                  answer: {
                    [k: string]: unknown;
                  }[];
                  id?: string;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'faq';
              }
            | {
                maxWidth: 'full' | 'large' | 'medium';
                listType: 'unordered' | 'ordered';
                cards: {
                  heading: string;
                  icon: string;
                  content: {
                    [k: string]: unknown;
                  }[];
                  id?: string;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'featureCards';
              }
            | {
                layout?: (
                  | {
                      content: {
                        [k: string]: unknown;
                      }[];
                      id?: string;
                      blockName?: string;
                      blockType: 'content';
                    }
                  | {
                      color: 'primary' | 'neutral';
                      variant: 'outlined' | 'solid';
                      size: 'sm' | 'md' | 'lg';
                      link: {
                        text: string;
                        icon?: string;
                        iconPosition: 'none' | 'left' | 'right';
                        newTab?: boolean;
                        type: 'reference' | 'external';
                        reference: {
                          value: string | Page;
                          relationTo: 'pages';
                        };
                        url: string;
                      };
                      margin?: boolean;
                      id?: string;
                      blockName?: string;
                      blockType: 'buttonLink';
                    }
                  | {
                      questions?: {
                        question: string;
                        answer: {
                          [k: string]: unknown;
                        }[];
                        id?: string;
                      }[];
                      id?: string;
                      blockName?: string;
                      blockType: 'faq';
                    }
                )[];
                id?: string;
                blockName?: string;
                blockType: 'scrollSection';
              }
          )[];
          id?: string;
          blockName?: string;
          blockType: 'heroSection';
        }
      | {
          maxWidth: 'full' | 'large' | 'medium';
          heading: string;
          description: string;
          ctaButton?: boolean;
          buttonLink?: {
            color: 'primary' | 'neutral';
            variant: 'outlined' | 'solid';
            size: 'sm' | 'md' | 'lg';
            link: {
              text: string;
              icon?: string;
              iconPosition: 'none' | 'left' | 'right';
              newTab?: boolean;
              type: 'reference' | 'external';
              reference: {
                value: string | Page;
                relationTo: 'pages';
              };
              url: string;
            };
            id?: string;
          };
          id?: string;
          blockName?: string;
          blockType: 'heroPage';
        }
      | {
          maxWidth: 'full' | 'large' | 'medium';
          sectionId: string;
          layout?: (
            | {
                content: {
                  [k: string]: unknown;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'content';
              }
            | {
                color: 'primary' | 'neutral';
                variant: 'outlined' | 'solid';
                size: 'sm' | 'md' | 'lg';
                link: {
                  text: string;
                  icon?: string;
                  iconPosition: 'none' | 'left' | 'right';
                  newTab?: boolean;
                  type: 'reference' | 'external';
                  reference: {
                    value: string | Page;
                    relationTo: 'pages';
                  };
                  url: string;
                };
                margin?: boolean;
                id?: string;
                blockName?: string;
                blockType: 'buttonLink';
              }
            | {
                questions?: {
                  question: string;
                  answer: {
                    [k: string]: unknown;
                  }[];
                  id?: string;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'faq';
              }
            | {
                maxWidth: 'full' | 'large' | 'medium';
                listType: 'unordered' | 'ordered';
                cards: {
                  heading: string;
                  icon: string;
                  content: {
                    [k: string]: unknown;
                  }[];
                  id?: string;
                }[];
                id?: string;
                blockName?: string;
                blockType: 'featureCards';
              }
            | {
                packages: {
                  emphasize?: boolean;
                  heading: string;
                  icon: string;
                  description?: {
                    [k: string]: unknown;
                  }[];
                  itemGroups: {
                    heading: string;
                    icon: string;
                    items: {
                      text: string;
                      superscript?: string;
                      id?: string;
                    }[];
                    id?: string;
                  }[];
                  pricing: {
                    price: number;
                    description?: string;
                    buttonLink: {
                      color: 'primary' | 'neutral';
                      variant: 'outlined' | 'solid';
                      size: 'sm' | 'md' | 'lg';
                      link: {
                        text: string;
                        icon?: string;
                        iconPosition: 'none' | 'left' | 'right';
                        newTab?: boolean;
                        type: 'reference' | 'external';
                        reference: {
                          value: string | Page;
                          relationTo: 'pages';
                        };
                        url: string;
                      };
                      id?: string;
                    };
                    footnote?: string;
                  };
                  id?: string;
                }[];
                footnotes?: {
                  superscript: string;
                  text: string;
                  id?: string;
                }[];
                showCustomPackage?: boolean;
                customPackage?: {
                  heading: string;
                  description: {
                    [k: string]: unknown;
                  }[];
                  buttonLink: {
                    color: 'primary' | 'neutral';
                    variant: 'outlined' | 'solid';
                    size: 'sm' | 'md' | 'lg';
                    link: {
                      text: string;
                      icon?: string;
                      iconPosition: 'none' | 'left' | 'right';
                      newTab?: boolean;
                      type: 'reference' | 'external';
                      reference: {
                        value: string | Page;
                        relationTo: 'pages';
                      };
                      url: string;
                    };
                    id?: string;
                  };
                };
                id?: string;
                blockName?: string;
                blockType: 'packageCards';
              }
            | {
                layout?: (
                  | {
                      content: {
                        [k: string]: unknown;
                      }[];
                      id?: string;
                      blockName?: string;
                      blockType: 'content';
                    }
                  | {
                      color: 'primary' | 'neutral';
                      variant: 'outlined' | 'solid';
                      size: 'sm' | 'md' | 'lg';
                      link: {
                        text: string;
                        icon?: string;
                        iconPosition: 'none' | 'left' | 'right';
                        newTab?: boolean;
                        type: 'reference' | 'external';
                        reference: {
                          value: string | Page;
                          relationTo: 'pages';
                        };
                        url: string;
                      };
                      margin?: boolean;
                      id?: string;
                      blockName?: string;
                      blockType: 'buttonLink';
                    }
                  | {
                      questions?: {
                        question: string;
                        answer: {
                          [k: string]: unknown;
                        }[];
                        id?: string;
                      }[];
                      id?: string;
                      blockName?: string;
                      blockType: 'faq';
                    }
                )[];
                id?: string;
                blockName?: string;
                blockType: 'scrollSection';
              }
          )[];
          id?: string;
          blockName?: string;
          blockType: 'section';
        }
    )[];
  };
  updatedAt: string;
  createdAt: string;
  _status?: 'draft' | 'published';
}
export interface Media {
  id: string;
  alt?: string;
  base64?: string;
  updatedAt: string;
  createdAt: string;
  url?: string;
  filename?: string;
  mimeType?: string;
  filesize?: number;
  width?: number;
  height?: number;
  sizes?: {
    preview?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
    thumbnail?: {
      url?: string;
      width?: number;
      height?: number;
      mimeType?: string;
      filesize?: number;
      filename?: string;
    };
  };
}
export interface Navigation {
  id: string;
  links?: {
    text: string;
    icon?: string;
    iconPosition: 'none' | 'left' | 'right';
    newTab?: boolean;
    type: 'reference' | 'external';
    reference: {
      value: string | Page;
      relationTo: 'pages';
    };
    url: string;
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
export interface Footer {
  id: string;
  socialLinks?: {
    text: string;
    icon?: string;
    iconPosition: 'none' | 'left' | 'right';
    newTab?: boolean;
    type: 'reference' | 'external';
    reference: {
      value: string | Page;
      relationTo: 'pages';
    };
    url: string;
    id?: string;
  }[];
  updatedAt?: string;
  createdAt?: string;
}
